### ISSUE TITLE
Update needed on maximum size of merging digest size.

### ISSUE THREAD

**Issue by tdunning** [vega/datalib-sketch#3]
I apologize for the incorrect comment in my original Java code about the maximum size for a merging digest.  In fact, the bound is 2 * ceiling(compression), not as in the code.  

This changes this line: https://github.com/vega/datalib-sketch/blob/master/src/t-digest.js#L20

Here is a proof:

In the algorithm, we convert q values to k values using 

k = compression * (asin(2 * q - 1) + \pi / 2) / \pi

For q = 1, k_max = compression. This is the largest possible value k can have and the number of centroids is less than or equal to ceiling(2 * compression). We only consider cases where compression >= 1 which implies that we have 2 or more centroids.

Take n as the number of centroids. The sum of the k-sizes for these centroids must be exactly k_max. 

If n is even, then suppose that n > 2 ceiling(k_max). Further, to avoid collapse to a smaller number of centroids, we know that all adjacent pairs of centroid weights must be greater than 1. But we can form k_max consecutive pairs which must add up to more than k_max. This implies that the weights on the items after the k_max pairs must be negative which is impossible. Thus, n > 2 ceiling(k_max) is impossible for even n.

If n is odd, then we will have n > 2 ceiling(k_max) + 1 if n > 2 ceiling(k_max). Again, we can form at least k_max pairs, each with k_size greater than 1. There will be at least 3 centroids after these pairs. But this implies that the k-size of the remaining centroids will be less than or equal to one. But the first two of these must have k-size together greater or equal to one so the remaining centroids must have negative k-size. Thus, n > 2 ceiling(k_max) + 1 > 2 ceiling(k_max) is impossible for n odd. 

By contradiction, n <= 2 ceiling(compression)

**Comment by jheer** [comment]
Thanks @tdunning! Fixed in 89f9aee.

**Comment by tdunning** [comment]
ceiling(2 k_max) != 2 ceiling(k_max)

**Comment by jheer** [comment]
Indeed. Fixed in 590d43e. Thanks!
